### PR TITLE
Added functionality for user to submit feedback report

### LINKED ISSUE #53: Settings Page - quality of life change
Currently the settings page has two tabs
- Settings
- Delete Account

image

This looks a little bit awkward as a new user might have trouble identifying which tab they are currently on. So, it would be a good idea to add a new tab to help act as a differentiation (3 is better than 2). This new tab would serve as a "contact us" for bug reports, and we'll simply log the user response into our requests.txt (or some other file) or just not log it at all.

### PR DESCRIPTION
**Pull request by hsorathia**
Resolves #53 

New changes:
- Nav bar tabs are colored differently to match with theme better
- New tab to help user differentiate between tabs and which one they're on
- Contact us tab allows the user to submit reports about their experience

New settings page looks like this
image

Feedback page:
image

Upon successful submission:
image

Feedback is stored in `/log/userReport.txt`
image

### CODE REVIEW

**Review by realCalvin — APPROVED** [review]
is the 2nd tab in the first picture supposed to be black?

**Comment by hsorathia** [comment]
> is the 2nd tab in the first picture supposed to be black?

That's just the current hover effect on the tab which makes the become black. I can change it to white if you think it looks off

**Comment by realCalvin** [comment]
> > is the 2nd tab in the first picture supposed to be black?
> 
> That's just the current hover effect on the tab which makes the become black. I can change it to white if you think it looks off

yeah it's hard to read. maybe try gray or a shade of white

**Comment by hsorathia** [comment]
> > > is the 2nd tab in the first picture supposed to be black?
> > 
> > 
> > That's just the current hover effect on the tab which makes the become black. I can change it to white if you think it looks off
> 
> yeah it's hard to read. maybe try gray or a shade of white

peep this

image

**Comment by realCalvin** [comment]
clean 🧼

**Pull request merged**
