### PR TITLE
bugfixes

### LINKED ISSUE #66: Bugfixes
A couple bugs in our website:
image

image

### PR DESCRIPTION
**Pull request by hsorathia**
Resolves #66

New changes:
- Adjusted table values for tables using `username` as a FK to 15 characters
- Added key to column props that were being dynamically rendered
- Added reward alert to the top of the home page in the form of an alert (untested)
- Fixed Logo missing from shop frontend
- Removed user_profile tables as it was redundant on the user

### CODE REVIEW

**Review by realCalvin — APPROVED** [review]
image

looks good but it stays at the top until you navigate somewhere else--which can be annoying. Should add a timeout function that changes the state back to false after 3 seconds or something.

`
        window.setTimeout(() => {
          this.setState({ dailyReward: false })
        }, 3000)
`

**Comment by hsorathia** [comment]
> image
> 
> looks good but it stays at the top until you navigate somewhere else--which can be annoying. Should add a timeout function that changes the state back to false after 3 seconds or something.
> 
> `window.setTimeout(() => { this.setState({ dailyReward: false }) }, 3000)`

image

Like this?

**Comment by realCalvin** [comment]
> > image
> > looks good but it stays at the top until you navigate somewhere else--which can be annoying. Should add a timeout function that changes the state back to false after 3 seconds or something.
> > `window.setTimeout(() => { this.setState({ dailyReward: false }) }, 3000)`
> 
> image
> 
> Like this?

yea

**Comment by hsorathia** [comment]
ok it done then

**Comment by realCalvin** [comment]
another bug that Tien found.
On his shop page it shows up as a blank square. (blank for mine) was there supposed to be an icon for the shop page?

https://github.com/jerrylee17/casino/blob/12bd98b35405012ee05d93ec28ce03692f86514c/src/Pages/Shop/Shop.js#L73

Edit: yea it should be src={Logo}

**Comment by TimTran115** [comment]
> 
> 
> another bug that Tien found.
> On his shop page it shows up as a blank square. (blank for mine) was there supposed to be an icon for the shop page?
> 
> https://github.com/jerrylee17/casino/blob/12bd98b35405012ee05d93ec28ce03692f86514c/src/Pages/Shop/Shop.js#L73

I remember when Tiff design the shop page, she added an icon next to it. It the shop logo in the images folder

**Pull request merged**
